environment:

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip and setuptools to avoid displaying
  # warnings about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install --upgrade setuptools"
  
  - ps: echo $env:PYTHON
  - "pip install pytest"
  - "pip install pytest-cov"
  # set the integration test environment variable
  - "SET EPPY_INTEGRATION=TRUE"

build: off

test_script:
  # Test command.
  - "%PYTHON%\\python.exe setup.py test"
